server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
#Logging
logging:
  level:
    com.test: INFO
    org.springframework: INFO
  file: logs/discovery-service.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
    level: DEBUG